"""
Safe execution of LLM-generated extraction scripts.
"""
import re
import json
from datetime import datetime, date
from typing import Dict, Any


class ScriptRunner:
    """Safely execute extraction scripts generated by the LLM."""

    @staticmethod
    def run(script_body: str, raw_text: str) -> Dict[str, Any]:
        """
        Execute an extraction script safely.
        
        Args:
            script_body: Python code string to execute
            raw_text: Document text to extract from
            
        Returns:
            Dictionary with extracted field values
        """
        # Validate script before execution
        is_valid, error_msg = ScriptRunner.validate_script(script_body)
        if not is_valid:
            print(f"Script validation error: {error_msg}")
            return {}
        
        import re
        import json
        from datetime import datetime, date

        lines = script_body.split('\n')
        cleaned_lines = [line for line in lines if not line.strip().startswith('import ') and not line.strip().startswith('from ')]
        cleaned_script = '\n'.join(cleaned_lines)

        safe_builtins = {
            'len': len,
            'str': str,
            'int': int,
            'float': float,
            'bool': bool,
            'list': list,
            'dict': dict,
            'tuple': tuple,
            'set': set,
            'range': range,
            'enumerate': enumerate,
            'zip': zip,
            'map': map,
            'filter': filter,
            'min': min,
            'max': max,
            'sum': sum,
            'sorted': sorted,
            're': re,
            'json': json,
            'datetime': datetime,
            'date': date,
            'None': None,
            'True': True,
            'False': False,
        }

        local_scope = {
            'raw_text': raw_text,
            'result': {},
            're': re,
            'json': json,
            'datetime': datetime,
            'date': date,
        }

        try:
            exec(cleaned_script, {"__builtins__": safe_builtins}, local_scope)
            result = local_scope.get('result', {})
            
            if not isinstance(result, dict):
                result = {}
            
            return result
        except Exception as e:
            print(f"Script execution error: {e}")
            return {}

    @staticmethod
    def validate_script(script_body: str) -> tuple[bool, str]:
        """
        Validate a script before execution.
        Returns (is_valid, error_message)
        """
        dangerous_patterns = [
            'import os',
            'import sys',
            '__import__',
            'exec(',
            'eval(',
            'open(',
            'subprocess',
            'socket',
        ]

        for pattern in dangerous_patterns:
            if pattern in script_body:
                return False, f"Dangerous pattern detected: {pattern}"

        try:
            compile(script_body, '<string>', 'exec')
            return True, ""
        except SyntaxError as e:
            return False, f"Syntax error: {e}"
