"""
Safe execution of LLM-generated extraction scripts.
"""
import json
from typing import Dict, Any


class ScriptRunner:
    """Safely execute extraction scripts generated by the LLM."""

    @staticmethod
    def run(script_body: str, raw_text: str) -> Dict[str, Any]:
        """
        Execute an extraction script safely.
        
        Args:
            script_body: Python code string to execute
            raw_text: Document text to extract from
            
        Returns:
            Dictionary with extracted field values
        """
        # Setup safe environment
        safe_builtins = {
            'len': len,
            'str': str,
            'int': int,
            'float': float,
            'bool': bool,
            'list': list,
            'dict': dict,
            'tuple': tuple,
            'set': set,
            'None': None,
            'True': True,
            'False': False,
        }

        # Allowed imports
        import re
        import json as json_module
        from datetime import datetime, date

        allowed_modules = {
            're': re,
            'json': json_module,
            'datetime': datetime,
            'date': date,
        }

        # Local scope for script execution
        local_scope = {
            'raw_text': raw_text,
            'result': {},
            're': re,
            'json': json_module,
            'datetime': datetime,
            'date': date,
        }

        try:
            # Execute the script with restricted environment
            exec(script_body, {"__builtins__": safe_builtins}, local_scope)
            result = local_scope.get('result', {})
            
            # Ensure result is a dict
            if not isinstance(result, dict):
                result = {}
            
            return result
        except Exception as e:
            # Log the error and return empty result
            print(f"Script execution error: {e}")
            return {}

    @staticmethod
    def validate_script(script_body: str) -> tuple[bool, str]:
        """
        Validate a script before execution.
        Returns (is_valid, error_message)
        """
        # Check for dangerous patterns
        dangerous_patterns = [
            'import os',
            'import sys',
            '__import__',
            'exec(',
            'eval(',
            'open(',
            'subprocess',
            'socket',
        ]

        for pattern in dangerous_patterns:
            if pattern in script_body:
                return False, f"Dangerous pattern detected: {pattern}"

        # Try to compile the script
        try:
            compile(script_body, '<string>', 'exec')
            return True, ""
        except SyntaxError as e:
            return False, f"Syntax error: {e}"
